### ISSUE TITLE
html file not loading model in viewer

### ISSUE THREAD

**Issue by gaparicio** [Developer-Autodesk/View-and-Data-Barebone#2]
Works perfect when going through the steps at (http://www.shiyaluo.com/Intro-View-and-Data/) but, html file does not load model after replacing tocken and urn.

**Comment by shiya** [comment]
Can you share the console log with me?

**Comment by gaparicio** [comment]
![00](https://cloud.githubusercontent.com/assets/1442355/9855630/62be679e-5ac4-11e5-9150-d9be0b482253.JPG)
![01](https://cloud.githubusercontent.com/assets/1442355/9855631/62bf6bee-5ac4-11e5-9baa-7540450a2b94.JPG)

**Comment by gaparicio** [comment]
Please see attached

**Comment by shiya** [comment]
You need to run the page on a server or change the security settings. WebGL loads additional assets from external sources, the files need to be delivered via HTTP.
Read more about it here: https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally
